baseURL = 'https://www.mikeshi.me/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
title = 'Mike Shi Blog'
theme = 'diary'
[params]
  author = 'Mike Shi'
  subtitle = "Mike Shiçš„æŠ€æœ¯è‡ªç•™åœ°"
  [params.contract]
  email = "mikeshi80@gmail.com"
[services]
  [services.googleAnalytics]
    ID = 'G-YM6RPDDXGZ'
[[menu.main]]
url = "/categories"
name = "ğŸ—ƒåˆ†ç±»"
weight = 2
[[menu.main]]
url = "/tags"
name = "ğŸ·æ ‡ç­¾"
weight = 3
[[menu.main]]
url = "/posts"
name = "ğŸ“‹å½’æ¡£"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "ğŸ“¶ RSS"
weight = 4